name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./fmh-android/

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./fmh-android/

  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./fmh-android/
      - name: Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest --info
          working-directory: ./fmh-android/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Report_index.html
          path: ./fmh-android/app/build/reports/androidTests/connected/ 
        
  report:
    runs-on: ubuntu-latest
    needs: android_tests 
    if: ${{ always() }} 
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: Report_index.html
